- name: Build with Maven
  run: mvn clean package assembly:single

- name: Create executable with jpackage
  run: |
    jpackage --input target --name SQL-Insert-Converter --main-jar SQL-Insert-Converter.jar --main-class com.example.gldb.HelloApplication --type exe --win-menu --win-shortcut --app-version 1.0 --vendor HiProfession --dest target/dist
